remote_theme: thelehhman/texture
title: Mark Gravestock's Home on the Web
permalink: /posts/:title/

texture:
  title: Mark Gravestock
  tagline: Developer. Agile Practitioner.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true

  social_links:
    github:  markgravestock
    linkedIn: in/mark-gravestock
